# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 15:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleModel',
            fields=[
            ],
        ),
    ]
